nome = input("Digite seu nome: ")
idade = int(input("Informe sua idade: "))
cidade = input("Qual sua cidade natal? ")
print("O tamanho do nome é: ")
tamanho = len(nome)
print(tamanho)
letras = nome.count("a")
print(f"A quantidade de letra A que contém no nome {nome} é: ")
print(letras)
no = nome.upper()
print("Seu nome com letras maiúsculas: ")
print(no)

print("{} tem, {} anos, e sua cidade natal é {}".format(nome, idade, cidade))