
CREATE TABLE ALUNO (
    ID_ALUNO INT PRIMARY KEY,
    NOME_ALUNO VARCHAR(50) NOT NULL,
    DATA_NASCIMENTO VARCHAR(10) NOT NULL,
    ENDERECO VARCHAR(100) NOT NULL,
    CONTATO VARCHAR(20) NOT NULL
);


CREATE TABLE LIVRO (
    ID_LIVRO INT PRIMARY KEY,
    TITULO VARCHAR(50) NOT NULL,
    AUTOR VARCHAR(50) NOT NULL,
    ANO_LANCAMENTO INT NOT NULL,
    QUANTIDADE INT NOT NULL
);

ALTER TABLE ALUNO
ADD DATA_NASCIMENTO VARCHAR(10) NOT NULL;

ALTER TABLE ALUNO
RENAME COLUMN TELEFONE TO CONTATO;

ALTER TABLE LIVRO
ADD ISBN VARCHAR(13) NOT NULL;

ALTER TABLE LIVRO
DROP COLUMN ISBN;
